apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnoe-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cnoe-platform
      app.kubernetes.io/component: platform-services
      app.kubernetes.io/managed-by: kustomize
